version: "1"

services:
  fastapi:
    build: ./api/.
    ports:
      - 8000:8000
  
  caddy:
    build: ./caddy/.
    depends_on:
      - fastapi
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    ports:
      - 80:80
      - 443:443

volumes:
  caddy_data:
  caddy_config: