version: "3.7"

services:
  fastapi:
    build: ./api/.
    expose:
      - 8000

  db:
    image: postgres:14.1-alpine
    restart: "always"
    environment:
      - POSTGRES_PASSWORD=bWFyaW5lbW9uZXliYW5raW5nMjAyNCEhIQ==
      - POSTGRES_DB=marine
      - POSTGRES_USER=admin
      - DB_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  caddy_data:
  caddy_config:
  db:
    driver: local