version: "3.7"

services:
  fastapi:
    build: ./api/.
  
  caddy:
    build: ./caddy/.
    depends_on:
      - fastapi
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    network_mode: "host"

volumes:
  caddy_data:
  caddy_config: